apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pengujian-skenario-env-statefulset
spec:
  serviceName: pengujian-skenario-env-statefulset
  replicas: 2
  selector:
    matchLabels:
      app: pengujian-skenario-env-statefulset
  template:
    metadata:
      labels:
        app: pengujian-skenario-env-statefulset
        env-secret-secured: "true"
    spec:
      initContainers: # secret definition here, not on the "main" containers
      - name: create-env-file
        image: kadeksuryam/init-container-secret:latest
        imagePullPolicy: Always
        env:
        # proxy ITB, initContainer's process need to access internet
        - name: HTTP_PROXY
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        - name: HTTPS_PROXY
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        - name: http_proxy
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        - name: https_proxy
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        # secrets definition start
        - name: USERNAME1
          valueFrom:
              secretKeyRef:
                name: pengujian-skenario-env-secret1
                key: USERNAME
        - name: PASSWORD1
          valueFrom:
              secretKeyRef:
                name: pengujian-skenario-env-secret1
                key: PASSWORD
        - name: USERNAME2
          valueFrom:
              secretKeyRef:
                name: pengujian-skenario-env-secret2
                key: USERNAME
        - name: PASSWORD2
          valueFrom:
              secretKeyRef:
                name: pengujian-skenario-env-secret2
                key: PASSWORD
        # secrets definition end
        - name: IMAGE_NAME # mandatory, same as the containers[0].image below
          value: kadeksuryam/pengujian-skenario-env:latest
        volumeMounts: # mandatory
        - name: init-vol
          mountPath: /vol
      containers:
      - name: pengujian-skenario-env-statefulset
        image:  kadeksuryam/pengujian-skenario-env:latest
        command:
        - /vol/init.sh
        volumeMounts:
        - name: init-vol
          mountPath: /vol
      volumes: # mandatory
      - name: init-vol
        emptyDir: {}
