apiVersion: apps/v1
kind: Deployment
metadata:
  name: pengujian-integrasi-container-compromised-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pengujian-integrasi-container-compromised-deployment
  template:
    metadata:
      labels:
        app: pengujian-integrasi-container-compromised-deployment
        env-secret-secured: "true"
        mf-secret-secured: "true"
    spec:
      initContainers: # secret definition here, not on the "main" containers
      - name: create-env-file
        image: kadeksuryam/init-container-secret:latest
        imagePullPolicy: Always
        env:
        # proxy ITB, initContainer's process need to access internet
        - name: HTTP_PROXY
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        - name: HTTPS_PROXY
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        - name: http_proxy
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        - name: https_proxy
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        # secrets definition start
        - name: SECRET_V1_USERNAME_ENV
          valueFrom:
              secretKeyRef:
                name: pengujian-integrasi-container-compromised-secret-v1
                key: USERNAME
        - name: SECRET_V1_PASSWORD_ENV
          valueFrom:
              secretKeyRef:
                name: pengujian-integrasi-container-compromised-secret-v1
                key: PASSWORD
        - name: SECRET_V2_USERNAME_ENV
          valueFrom:
              secretKeyRef:
                name: pengujian-integrasi-container-compromised-secret-v2
                key: USERNAME
        - name: SECRET_V2_PASSWORD_ENV
          valueFrom:
              secretKeyRef:
                name: pengujian-integrasi-container-compromised-secret-v2
                key: PASSWORD
        # secrets definition end
        - name: IMAGE_NAME # mandatory, same as the containers[0].image below
          value: kadeksuryam/spring4shell-app-example-integrasi:latest
        volumeMounts: # mandatory
        - name: init-vol
          mountPath: /vol
      containers:
      - name: pengujian-integrasi-container-compromised-deployment
        image:  kadeksuryam/spring4shell-app-example-integrasi:latest
        imagePullPolicy: Always
        command:
        - /vol/init.sh
        env:
        - name: SECRET_V1_USERNAME_PATH
          value: /etc/secret-v1/USERNAME
        - name: SECRET_V1_PASSWORD_PATH
          value: /etc/secret-v1/PASSWORD
        - name: SECRET_V2_USERNAME_PATH
          value: /etc/secret-v2/USERNAME
        - name: SECRET_V2_PASSWORD_PATH
          value: /etc/secret-v2/PASSWORD
        volumeMounts:
        - name: init-vol
          mountPath: /vol
        - name: secret-v1-volume
          mountPath: "/etc/secret-v1"
          readOnly: true
        - name: secret-v2-volume
          mountPath: "/etc/secret-v2"
          readOnly: true
        readinessProbe:
          httpGet:
            path: /app/greeting
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes: # mandatory
      - name: init-vol
        emptyDir: {}
      - name: secret-v1-volume
        secret:
          secretName: pengujian-integrasi-container-compromised-secret-v1
      - name: secret-v2-volume
        secret:
          secretName: pengujian-integrasi-container-compromised-secret-v2
