apiVersion: v1
kind: Secret
metadata:
  namespace: surya
  name: deployment-env-secret
type: Opaque
data:
  api-key: bXktc2VjcmV0LXZhbHVl # my-secret-value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: surya
  name: deployment-env-secret-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-env-secret-test
  template:
    metadata:
      labels:
        app: deployment-env-secret-test
        env-secret-secured: "true"
    spec:
      initContainers:
      - name: create-env-file
        image: kadeksuryam/init-container-secret:latest
        imagePullPolicy: Always
        env:
        - name: IMAGE_NAME
          value: kadeksuryam/busybox
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: api-key
        volumeMounts:
        - mountPath: /vol
          name: init-vol
      containers:
      - name: busybox
        image:  kadeksuryam/busybox
        command:
        - /vol/init.sh
        args:
        - "--test"
        - "args"
        volumeMounts:
        - name: init-vol
          mountPath: /vol
      volumes:
      - name: init-vol
        emptyDir: {}
