apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pengujian-skenario-mounted-file-statefulset
spec:
  serviceName: pengujian-skenario-mounted-file-statefulset
  replicas: 2
  selector:
    matchLabels:
      app: pengujian-skenario-mounted-file-statefulset
  template:
    metadata:
      labels:
        app: pengujian-skenario-mounted-file-statefulset
        mf-secret-secured: "true"
    spec:
      containers:
      - name: pengujian-skenario-mounted-file-statefulset
        image: kadeksuryam/pengujian-skenario-mounted-file:latest
        env:
        - name: SECRET1_USERNAME_PATH
          value: /etc/secret1/USERNAME
        - name: SECRET1_PASSWORD_PATH
          value: /etc/secret1/PASSWORD
        - name: SECRET2_USERNAME_PATH
          value: /etc/secret2/USERNAME
        - name: SECRET2_PASSWORD_PATH
          value: /etc/secret2/PASSWORD
        volumeMounts:
        - name: secret1-volume
          mountPath: "/etc/secret1"
          readOnly: true
        - name: secret2-volume
          mountPath: "/etc/secret2"
          readOnly: true
      volumes:
      - name: secret1-volume
        secret:
          secretName: pengujian-skenario-mounted-file-secret1
      - name: secret2-volume
        secret:
          secretName: pengujian-skenario-mounted-file-secret2
