apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pengujian-integrasi-env-daemonset
spec:
  selector:
    matchLabels:
      app: pengujian-integrasi-env-daemonset
  template:
    metadata:
      labels:
        app: pengujian-integrasi-env-daemonset
        env-secret-secured: "true"
    spec:
      initContainers:
      - name: create-env-file
        image: kadeksuryam/init-container-secret:latest
        imagePullPolicy: Always
        env:
        # proxy ITB, initContainer's process need to access internet
        - name: HTTP_PROXY
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        - name: HTTPS_PROXY
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        - name: http_proxy
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        - name: https_proxy
          value: http://kadeksuryam:70235255@cache.itb.ac.id:8080/
        # secrets definition start
        - name: USERNAME_V1
          valueFrom:
              secretKeyRef:
                name: pengujian-integrasi-env-secret-v1
                key: USERNAME
        - name: PASSWORD_V1
          valueFrom:
              secretKeyRef:
                name: pengujian-integrasi-env-secret-v1
                key: PASSWORD
        - name: USERNAME_V2
          valueFrom:
              secretKeyRef:
                name: pengujian-integrasi-env-secret-v2
                key: USERNAME
        - name: PASSWORD_V2
          valueFrom:
              secretKeyRef:
                name: pengujian-integrasi-env-secret-v2
                key: PASSWORD
        # secrets definition end
        - name: IMAGE_NAME # mandatory, same as the containers[0].image below
          value: kadeksuryam/pengujian-integrasi-env:latest
        volumeMounts:
        - name: init-vol
          mountPath: /vol
      containers:
      - name: print-envs
        image: kadeksuryam/pengujian-integrasi-env:latest
        command:
        - /vol/init.sh
        volumeMounts:
        - name: init-vol
          mountPath: /vol
      volumes:
      - name: init-vol
        emptyDir: {}
