apiVersion: apps/v1
kind: Deployment
metadata:
  name: karmor-secret-controller-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karmor-secret-controller-test-deployment
  template:
    metadata:
      labels:
        app: karmor-secret-controller-test-deployment
    spec:
      containers:
      - name: karmor-secret-controller-test-deployment
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: karmor-secret-controller-test-secret
