apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: karmor-secret-controller-test-statefulset
spec:
  serviceName: karmor-secret-controller-test-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: karmor-secret-controller-test-statefulset
  template:
    metadata:
      labels:
        app: karmor-secret-controller-test-statefulset
    spec:
      containers:
      - name: karmor-secret-controller-test-statefulset
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret
