apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: karmor-secret-controller-test-daemonset
spec:
  selector:
    matchLabels:
      app: karmor-secret-controller-test-daemonset
  template:
    metadata:
      labels:
        app: karmor-secret-controller-test-daemonset
        env-secret-secured: "true"
    spec:
      initContainers:
      - name: create-env-file
        image: kadeksuryam/init-container-secret:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: karmor-secret-controller-test-secret
        env:
        - name: IMAGE_NAME
          value: kadeksuryam/print-envs:latest
        volumeMounts:
        - name: init-vol
          mountPath: /vol
      containers:
      - name: print-envs
        image:  kadeksuryam/print-envs:latest
        command:
        - /vol/init.sh
        args:
        - "--test"
        - "args"
        volumeMounts:
        - name: init-vol
          mountPath: /vol
      volumes:
      - name: init-vol
        emptyDir: {}